name: Android Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  buildApk:
    name: Build android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: env set
        uses: skiddph/actions-env@v1.0.3
        with:
          file: .env # default | a path or filename
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_LOGIN_PROTOCOL: ${{ secrets.FB_LOGIN_PROTOCOL }}
          FB_CLIENT_TOKEN: ${{ secrets.FB_CLIENT_TOKEN }}
      - name: create text env
        run: |
          ls -a
          cp .env newfile.txt
          ls -a

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: app.txt
          path: newfile.txt
          if-no-files-found: error

  # releaseApk:
  #   name: Release android APK
  #   needs: buildApk
  #   if: contains(github.ref, 'tags')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download APK from build
  #       uses: actions/download-artifact@v4.1.17
  #       with:
  #         name: apk
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.TOKEN }}

  #   with:
  #     tag_name: ${{ github.ref }}
  #     release_name: Release ${{ github.ref }}
  #     draft: false
  #     prerelease: false

  # - name: Upload Release APK
  #   id: upload_release_asset
  #   uses: actions/upload-release-asset@v1.0.1
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
  #   with:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }}
  #     asset_path: apk/app-release.apk
  #     asset_name: app-release.apk
  #     asset_content_type: application/zip
